name: Check unanswered threads

on:
  push:
    branches: [main]
    paths:
      - 'conversations/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Find unanswered threads
        run: uvx corrkit find-unanswered >> "$GITHUB_STEP_SUMMARY"
